name: Notbuk
description: My Developer Notebook
author: Jed Brazal

baseurl: /notbuk

theme: minimal-mistakes-jekyll
minimal_mistakes_skin    : "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true